# 사이트 기본 설정
title: "GitHub Actions Multilingual"
baseurl: "/github-actions-multilingual"  # GitHub Pages에서 사용하는 URL 경로
url: "https://glossybigbro.github.io"  # 사이트의 기본 URL
remote_theme: "mmistakes/minimal-mistakes@4.26.0"  # minimal-mistakes 테마 사용

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# 사이드바 설정
defaults:
  - scope:
      path: ""
      type: "docs" 
    values:
      layout: single
      sidebar: "docs"  # 기본 사이드바 이름 지정
      nav: "main"  # main으로 설정한 사이드바 메뉴 사용

  - scope:
      path: "en"  # 영어 문서 설정
      type: "docs"
    values:
      lang: "en"
      navigation: "navigation-en"  # 영어용 네비게이션 설정
      sidebar: "docs"
      nav: "main"

  - scope:
      path: "ko"  # 한국어 문서 설정
      type: "docs"
    values:
      lang: "ko"
      navigation: "navigation-ko"  # 한국어용 네비게이션 설정
      sidebar: "docs"
      nav: "main"

# 컬렉션 설정 (사이드바를 활성화하기 위한 문서 타입 지정)
collections:
  docs:
    output: true
    permalink: /:path/
