# 사이트 기본 설정
title: "GitHub Actions Multilingual"
baseurl: "/github-actions-multilingual"  # GitHub Pages에서 사용하는 URL 경로
url: "https://glossybigbro.github.io"  # 사이트의 기본 URL
remote_theme: "mmistakes/minimal-mistakes@4.26.0"  # minimal-mistakes 테마 사용

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# 사이드바 설정
defaults:
  # _docs
  - scope:
      path: ""
      type: "docs" 
    values:
      sidebar:
        nav: "docs"

  - scope:
      path: "en"
      type: "docs"
    values:
      lang: "en"
      navigation: "navigation-en"
      sidebar:
        nav: "docs"

  - scope:
      path: "ko"
      type: "docs"
    values:
      lang: "ko"
      navigation: "navigation-ko"
      sidebar:
        nav: "docs"
