# 기본 사이트 설정
title: "GitHub Actions Multilingual"
baseurl: "/github-actions-multilingual"  # GitHub Pages에서 사용하는 URL 경로
url: "https://glossybigbro.github.io"  # 사이트의 기본 URL
remote_theme: "mmistakes/minimal-mistakes@4.26.2"  # minimal-mistakes 테마 사용

# 사이드바 설정
defaults:
  - scope:
      path: ""
      type: "docs"  # 문서 유형 지정
    values:
      layout: single  # minimal-mistakes 기본 레이아웃
      sidebar:
        nav: "docs"  # 사이드바 메뉴 설정 (docs로 설정)

  - scope:
      path: "en"
    values:
      lang: "en"
      navigation: "navigation-en"
      sidebar: docs  # 영어 페이지에서 사이드바 표시

  - scope:
      path: "ko"
    values:
      lang: "ko"
      navigation: "navigation-ko"
      sidebar: docs  # 한국어 페이지에서 사이드바 표시

# 컬렉션 설정 (사이드바를 활성화하기 위한 문서 타입 지정)
collections:
  docs:
    output: true
    permalink: /:path/
