# 기본 사이트 설정
title: "GitHub Actions Multilingual"
baseurl: "/github-actions-multilingual"  # GitHub Pages에서 사용하는 URL 경로
url: "https://glossybigbro.github.io"  # 사이트의 기본 URL
remote_theme: "mmistakes/minimal-mistakes@4.24.0"  # minimal-mistakes 테마 사용

# 사이드바 설정
defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
      navigation: "navigation-en"  # 영어 네비게이션 파일 지정
      sidebar: "docs"  # 영어 페이지에서 사용할 사이드바 네비게이션 이름

  - scope:
      path: "ko"
    values:
      lang: "ko"
      navigation: "navigation-ko"  # 한국어 네비게이션 파일 지정
      sidebar: "docs"  # 한국어 페이지에서 사용할 사이드바 네비게이션 이름
